version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: resume-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: resumeuser
      POSTGRES_PASSWORD: resumepassword
      POSTGRES_DB: resumedb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - resume-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resume-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      ENVIRONMENT: development
      ALLOW_ORIGINS: "http://localhost:4200"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: resumeuser
      POSTGRES_PASSWORD: resumepassword
      POSTGRES_DB: resumedb
    networks:
      - resume-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: resume-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge

volumes:
  postgres-data: 